export const STR = {
  title: "BOLDER BRAWL",
  subtitle: "The Superhero Beatdown",
  p1label: "BOLDER BALLS",
  p2label: "COCKY",
  cpulabel: "NUT CRAKER",
  round: "ROUND",
  fight: "FIGHT!",
  ko: "K.O.!",
  win: "WINS!",
  draw: "DRAW!",
  pressStart: "PRESS ENTER OR TAP TO START",
  p1controls: "P1: WASD + G/H/J",
  p2controls: "P2: ARROWS + 1/2/3",
  selectFighter: "SELECT YOUR FIGHTER",
  vsText: "VS",
  roundOf: "BEST OF 3",
  charSelect1: "BOLDERBALLS",
  charSelect2: "COCKY",
  charSelect3: "NUTCRAKER",
  movesTitle: "MOVES",
  punchLight: "LIGHT PUNCH",
  punchHeavy: "HEAVY PUNCH",
  kick: "KICK",
  special: "SPECIAL",
  block: "BLOCK",
  jump: "JUMP",
  backDash: "BACK DASH",
  rematch: "REMATCH",
  menu: "MENU",
  tapToFight: "TAP TO ATTACK",
  health: "HP",
  special_meter: "POWER",
  comboText: "COMBO!",
  perfectText: "PERFECT!",
};
